### ISSUE TITLE
Migrate 'Test Report'

### ISSUE THREAD

**Issue by camilamaia** [loadsmart/peril-settings#11]
Migrate 'Test Report':
- https://github.com/loadsmart/dangerfile/blob/master/iOSDangerfile#L4-L7

**Comment by barbosa** [comment]
These reports are not working as expected anymore 😞 
As soon as we move all iOS projects to CircleCI 2.0, we can make use of its new way of publishing test reports.

**Comment by camilamaia** [comment]
@barbosa ok, sounds good to me.
